<?php require_once("header.phtml"); ?>

<h1>Login</h1>
<form method="post" action="login.php">
    <label>Username</label>
    <div class="input-control text full-size">
        <input name="username" type="text">
    </div>

    <label>Password</label>
    <div class="input-control password full-size">
        <input name="password" type="password">
    </div>

    <input type="submit" name="login">
</form>

<p><a href="register.php">I don't have an account</a> </p>

<?php require_once("footer.phtml"); ?>